import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainNavigation from "@/components/main-navigation/main-navigations";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spongeBoyMeBob = localFont({
  src: [
    {
      path: "../public/fonts/Spongeboy Me Bob.ttf",
      weight: "400",
    },
  ],
  variable: "--font-spongeBoyMeBob",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${spongeBoyMeBob.variable} bg-off-white font-['WorkSans',sans-serif]`}>
        <MainNavigation />
        {children}
      </body>
    </html>
  );
}
